


SELECT * FROM ASSISTENCIA..Sponsors_Contrato 
WHERE DESC_PRODUTO LIKE '%CETELEM%' 
AND CONTRATO = 1986
AND PRESTADORA LIKE  '% AFFINITY%'
AND STATUS = 'ATIVO'
ORDER BY CONTRATO  DESC


--Nota de refaturamento casos fora da bases

SELECT * FROM ASSISTENCIA..Sponsors_Contrato
WHERE  CONTRATO like '%02800%'

--685059

SELECT * FROM Nota_Fiscal WHERE NOTA_FISCAL = '002392'

BEGIN TRAN
DELETE NOTA_FISCAL 
WHERE NOTA_FISCAL = '002392'
AND ID = 19925

COMMIT

SELECT * FROM ASSISTENCIA..Nota_Fiscal WHERE NOTA_FISCAL = '00685060'  AND CONTRATO = 1530
SELECT sum(valor_total) FROM ASSISTENCIA..Nota_Fiscal
WHERE  Nota_Fiscal = '001916'
and contrato = '845'
order by TIME_STAMP desc


ROLLBACK
BEGIN TRAN
--DELETE FROM ASSISTENCIA..Nota_Fiscal WHERE NOTA_FISCAL = '0059'
AND ID = 19026

--COMMIT



ROLLBACK
BEGIN TRAN
UPDATE ASSISTENCIA..Nota_Fiscal
SET 
VALOR_TOTAL = 202.80
VALOR_ITEM = 202.80
WHERE  Nota_Fiscal = '002076'
AND ID = 18138
--COMMIT

SELECT * FROM ASSISTENCIA..Nota_Fiscal
WHERE  Nota_Fiscal = '002076'
AND ID = 18122
order by TIME_STAMP desc

SELECT * FROM ASSISTENCIA..Relatorio_Gerencial
WHERE PRODUTO = '@BET01'
OR PRODUTO = 'BDT002'
ORDER BY TIME_STAMP DESC



SELECT  * FROM SPONSORS_CONTRATO WHERE DESC_PRODUTO LIKE '%D2C%'
AND PRESTADORA = 'IKE'
AND SPONSOR LIKE '%CECRED%'
ORDER BY CONTRATO DESC

SELECT * FROM CTRL_OPERACOES..CTRL_SERVICOS WHERE Policy_Main_Product_Package_ID LIKE '%@BDPG3%'
ORDER BY time_stamp DESC
WHERE Flag_Assistencia = ''
AND Policy_Main_Product_Package_Desc LIKE '%B2C%'
ORDER BY TIME_STAMP DESC

SELECT COD_SPONSOR,PRODUTO,SPONSOR FROM Sponsors_Contrato WHERE PRODUTO = 'BDP773'


SELECT * FROM VIVO_HOMOLOGACAO..TMP_VENDAS
where Policy like '%01773%'
and [Policy Status] like '%activ%'


SELECT * FROM NOTA_FISCAL 
WHERE PRESTADORA LIKE '%INTER%'
--AND NOTA_FISCAL = '685063'
ORDER BY TIME_STAMP DESC



BEGIN TRAN 
DELETE FROM NOTA_FISCAL 
WHERE NOTA_FISCAL = '885483'
AND ID = 19930
COMMIT
SELECT * FROM Nota_Fiscal
WHERE NOTA_FISCAL = '885483'




