------------------------------------CETELEM------------------------------------

--DADOS FTP DATAFEED CETELEM
SELECT *
FROM	FTP_IMPLANTACOES..FTP_MOVE_FILE
WHERE	PRIORITY = '674'

--DADOS FTP ARQUIVO DE CANCELAMENTO CETELEM (ENVIO)
SELECT *
FROM	FTP_IMPLANTACOES..TB_DADOS_SFTP
WHERE	PRIORITY = 4

--INSERIR DADOS NO MOVE FTP
--PEGAR O MAIOR PRIORITY
SELECT MAX(PRIORITY)
FROM	FTP_IMPLANTACOES..FTP_MOVE_FILE

--INSERIR DADOS COM PRIORITY +1 DA QUERY ACIMA
INSERT INTO FTP_IMPLANTACOES..FTP_MOVE_FILE 
VALUES (707,'FTPACECETELEM','ASDSADSA','FTP4.DATAMOTION.COM.BR','\\LABRIFS02\PUBLIC\OPERAÇÕES\SPONSORS\CETELEM\S6_SEGURADOSMVTO\CANCELAMENTO_DIARIO',
'/CETELEM/CANCELAMENTO',1,21,1)



-------------------------------------CECRED-------------------------------------
--DATAFEED
SELECT *
FROM	DATAFEEDS..TMP_VENDAS
WHERE	[SPONSOR ID] = 'CV0'
AND		[POLICY MAIN PRODUCT PACKAGE ID] = '@BIE01'


--TEMPORARIA
SELECT *
FROM	RELATORIOS..TMP_DATAFEED_CECRED

--DADOS DO FTP DE ENVIO
SELECT *
 FROM FTP_IMPLANTACOES..FTP_MOVE_FILE
 WHERE PRIORITY = 705