DECLARE @NEITA NVARCHAR(1000), @EITA VARCHAR(1000)

SET @NEITA = (SELECT CAST(NOME AS VARCHAR(MAX)) collate SQL_Latin1_General_Cp1251_CS_AS FROM DBO.TIPTOE_BASICBOOK WHERE SEQ = 8)
SET @EITA = (SELECT CAST(NOME AS VARCHAR(MAX)) collate SQL_Latin1_General_Cp1251_CS_AS FROM DBO.TIPTOE_BASICBOOK WHERE SEQ = 8)

SELECT @NEITA, @EITA

†
SELECT TOP 100 * FROM DBO.TIPTOE_BASICBOOK

SELECT 
SEQ,
CAST(NOME AS VARCHAR(MAX)) collate SQL_Latin1_General_Cp1251_CS_AS,
TIPO,
DATA_NASC,
CPF,
MATRICULA,
TURMA
FROM DBO.TIPTOE_BASICBOOK

select cast(N'¡…’—Õ”⁄«√¿' as varchar(max)) collate SQL_Latin1_General_Cp1251_CS_AS
