
/*SELECT * FROM ASSISTENCIA..NOTA_FISCAL

select * from CTRL_OPERACOES..CTRL_OPERACIONAL


SELECT * FROM CTRL_OPERACOES..CTRL_SERVICOS
WHERE SPONSOR_ID = 'BZDC1'
OR SPONSOR_ID = 'BZDH1'
*/


SELECT * FROM ASSISTENCIA..SPONSORS_CONTRATO 
WHERE STATUS = 'ATIVO'
AND COD_SPONSOR LIKE '%BPE539%'



