use ANALISE_OPERACOES_TMP

select * from CECRED_REPORT
order by TIMESTAMP desc


SELECT 
SUBSTRING(LINHA,393,6) AS PRODUTO_S6,
*
FROM CECRED_REPORT
ORDER BY TIMESTAMP DESC

SELECT * FROM REPORT_CECRED_LIFE



SELECT SUBSTRING(LINHA,37,8) AS COOPERATIVA,
	COUNT(SUBSTRING(LINHA,37,8)) AS QTD_COOPERATIVA
FROM CECRED_REPORT
WHERE SUBSTRING(LINHA,37,8) LIKE '%CRE%'
GROUP BY SUBSTRING(LINHA,37,8)
ORDER BY QTD_COOPERATIVA DESC